// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.03 Use regions to block out Events and/or the player from\nbeing able to venture into those spots.","parameters":{"Player Restrict":"0","Event Restrict":"0","All Restrict":"0","Player Allow":"0","Event Allow":"0","All Allow":"0"}},
{"name":"YEP_X_VehicleRestrict","status":true,"description":"v1.00 (Req YEP_RegionRestrictions.js) This plugin allows you\nto control where vehicles can move and can land.","parameters":{"---Boat---":"","Boat Restrict":"0","Boat Allow":"0","Boat Land":"0","---Ship---":"","Ship Restrict":"0","Ship Allow":"0","Ship Land":"1","---Airship---":"","Airship Restrict":"0","Airship Allow":"0","Airship Land":"0"}}
];
